package export

import (
	"fmt"
	"os"
	"text/template"
	"time"

	"github.com/w1n/perfmon/internal/engine"
)

// markdownTemplate is the embedded Markdown report template.
// Code blocks use indentation (4 spaces) to avoid backtick issues in raw strings.
const markdownTemplate = `# perfmon Telemetry Report

**Generated:** {{ .Metadata.GeneratedAt }}
**Tool Version:** {{ .Metadata.PerfmonVersion }}
**Target:** {{ .Metadata.DeviceName }} ({{ .Metadata.TargetPlatform }})
**App:** {{ .Metadata.AppPackage }} [{{ .Metadata.BuildType }}]

---

## Metrics Summary

| Metric | Value |
|--------|-------|
| Duration | {{ .Summary.DurationSeconds }} samples |
| Peak CPU | {{ printf "%.1f" .Summary.PeakCPUPercent }}% |
| Average CPU | {{ printf "%.1f" .Summary.AverageCPUPercent }}% |
| Peak Memory | {{ formatBytes .Summary.PeakMemoryKB }} |
| Average Memory | {{ formatBytes .Summary.AverageMemoryKB }} |
| Peak Threads | {{ .Summary.PeakThreads }} |

---

## CPU Utilization

` + "```" + `
{{ .CPUSparkline }}
` + "```" + `

> Line chart (█ = value, ▓ = fill). Range: 0%–100%

---

## Memory Footprint

` + "```" + `
{{ .MemSparkline }}
` + "```" + `

> Line chart (█ = value, ▓ = fill). Values in MB

---

## Telemetry Data ({{ len .Telemetry }} samples)

| # | Timestamp | CPU (%) | Memory (KB) | Threads |
|---|-----------|---------|-------------|---------|
{{- range $i, $s := .Telemetry }}
| {{ add $i 1 }} | {{ formatUnix $s.Timestamp }} | {{ printf "%.1f" $s.CPUPercent }} | {{ $s.MemoryKB }} | {{ $s.Threads }} |
{{- end }}

---

*Generated by [perfmon](https://perfmon.qzz.io) v{{ .Metadata.PerfmonVersion }}*
`

// mdRenderer holds the data passed to the Markdown template.
type mdRenderer struct {
	ExportData
	CPUSparkline string
	MemSparkline string
}

// ExportMarkdown writes the export data as a Markdown file.
func ExportMarkdown(data ExportData, snapshots []engine.TelemetrySnapshot, opts Options) (string, error) {
	outPath := outputFilename(opts.OutputPath, FormatMD)

	f, err := os.Create(outPath)
	if err != nil {
		return "", err
	}
	defer f.Close()

	// Build ASCII sparklines for the report
	cpuSpark := buildASCIISparkline(snapshots, func(s engine.TelemetrySnapshot) float64 {
		return s.CPUPercent
	}, 0, 100)

	memSpark := buildASCIISparkline(snapshots, func(s engine.TelemetrySnapshot) float64 {
		return float64(s.MemoryKB) / 1024.0
	}, 0, 500)

	funcMap := template.FuncMap{
		"add": func(a, b int) int { return a + b },
		"formatBytes": func(kb int64) string {
			if kb < 1024 {
				return fmt.Sprintf("%d KB", kb)
			}
			return fmt.Sprintf("%.1f MB", float64(kb)/1024.0)
		},
		"formatUnix": func(ts int64) string {
			t := time.Unix(ts, 0)
			return t.Format("15:04:05")
		},
	}

	tmpl, err := template.New("markdown").Funcs(funcMap).Parse(markdownTemplate)
	if err != nil {
		return "", fmt.Errorf("template parse: %w", err)
	}

	renderer := mdRenderer{
		ExportData:   data,
		CPUSparkline: cpuSpark,
		MemSparkline: memSpark,
	}

	if err := tmpl.Execute(f, renderer); err != nil {
		return "", fmt.Errorf("template execute: %w", err)
	}

	return outPath, nil
}
