package export

import (
	_ "embed"
	"fmt"
	"os"
	"text/template"
	"time"

	"github.com/GAM3RG33K/perfmon-lite/internal/chart"
	"github.com/GAM3RG33K/perfmon-lite/internal/engine"
)

//go:embed templates/logo.txt
var asciiLogo string

// markdownTemplate is the embedded Markdown report template.
// Code blocks use indentation (4 spaces) to avoid backtick issues in raw strings.
const markdownTemplate = `{{ .AsciiLogo }}

# perfmon Telemetry Report

**Generated:** {{ .Metadata.GeneratedAt }}
**Tool Version:** {{ .Metadata.PerfmonVersion }}
**Target:** {{ .Metadata.DeviceName }} ({{ .Metadata.TargetPlatform }})
**App:** {{ .Metadata.AppPackage }} [{{ .Metadata.BuildType }}]

---

## Metrics Summary

| Metric | Value |
|--------|-------|
| Duration | {{ .Summary.DurationSeconds }} samples |
| Peak CPU | {{ printf "%.1f" .Summary.PeakCPUPercent }}% |
| Average CPU | {{ printf "%.1f" .Summary.AverageCPUPercent }}% |
| Peak Memory | {{ formatBytes .Summary.PeakMemoryKB }} |
| Average Memory | {{ formatBytes .Summary.AverageMemoryKB }} |
| Peak Threads | {{ .Summary.PeakThreads }} |

---

## CPU Utilization

` + "```" + `
{{ .CPUSparkline }}
` + "```" + `

> btop-style area chart (last {{ .ChartWindow }} samples)

---

## Memory Footprint

` + "```" + `
{{ .MemSparkline }}
` + "```" + `

> btop-style area chart (last {{ .ChartWindow }} samples)

---

## Telemetry Data ({{ len .Telemetry }} samples)

| # | Timestamp | CPU (%) | Memory (KB) | Threads | Stack |
|---|-----------|---------|-------------|---------|-------|
{{- range $i, $s := .Telemetry }}
| {{ add $i 1 }} | {{ formatUnix $s.Timestamp }} | {{ printf "%.1f" $s.CPUPercent }} | {{ $s.MemoryKB }} | {{ $s.Threads }} | {{ if $s.Stack }}Yes{{ else }}-{{ end }} |
{{- end }}

---

## Captured App Logs

{{- if .Logs }}
` + "```" + `
{{- range .Logs }}
{{ . }}
{{- end }}
` + "```" + `
{{- end }}

### Stack Traces

Samples with significant CPU usage (>50%) include kernel or user-space stack traces:

{{- range $i, $s := .Telemetry }}
{{- if $s.Stack }}
**Sample {{ add $i 1 }}** (CPU={{ printf "%.1f" $s.CPUPercent }}% at {{ formatUnix $s.Timestamp }})

` + "```" + `
{{ $s.Stack }}
` + "```" + `

{{- end }}
{{- end }}

---

*Generated by [perfmon](https://perfmon.qzz.io) v{{ .Metadata.PerfmonVersion }}*
`

// mdRenderer holds the data passed to the Markdown template.
type mdRenderer struct {
	ExportData
	CPUSparkline string
	MemSparkline string
	AsciiLogo    string
	ChartWindow  int
}

// ExportMarkdown writes the export data as a Markdown file.
func ExportMarkdown(data ExportData, snapshots []engine.TelemetrySnapshot, opts Options) (string, error) {
	outPath := outputFilename(opts.OutputPath, FormatMD)

	f, err := os.Create(outPath)
	if err != nil {
		return "", err
	}
	defer f.Close()

	plotW := chart.DefaultWidth
	cpuSpark := chart.RenderCPUChart(snapshots, plotW)
	memSpark := chart.RenderMemoryChart(snapshots, plotW)

	funcMap := template.FuncMap{
		"add": func(a, b int) int { return a + b },
		"formatBytes": func(kb int64) string {
			if kb < 1024 {
				return fmt.Sprintf("%d KB", kb)
			}
			return fmt.Sprintf("%.1f MB", float64(kb)/1024.0)
		},
		"formatUnix": func(ts int64) string {
			t := time.Unix(ts, 0)
			return t.Format("15:04:05")
		},
	}

	tmpl, err := template.New("markdown").Funcs(funcMap).Parse(markdownTemplate)
	if err != nil {
		return "", fmt.Errorf("template parse: %w", err)
	}

	renderer := mdRenderer{
		ExportData:   data,
		CPUSparkline: cpuSpark,
		MemSparkline: memSpark,
		AsciiLogo:    asciiLogo,
		ChartWindow:  chart.MaxPoints,
	}

	if err := tmpl.Execute(f, renderer); err != nil {
		return "", fmt.Errorf("template execute: %w", err)
	}

	return outPath, nil
}
