package export

import (
	"fmt"

	"github.com/go-pdf/fpdf"
	"github.com/GAM3RG33K/perfmon-lite/internal/engine"
)

// ExportPDF writes the export data as a PDF file with vector charts.
func ExportPDF(data ExportData, snapshots []engine.TelemetrySnapshot, opts Options) (string, error) {
	outPath := outputFilename(opts.OutputPath, FormatPDF)

	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.AddPage()

	// ── Title ──────────────────────────────────────────────────────────
	pdf.SetFont("Helvetica", "B", 20)
	pdf.SetTextColor(0, 255, 255) // cyan
	pdf.CellFormat(0, 12, "perfmon Telemetry Report", "", 1, "L", false, 0, "")
	pdf.Ln(4)

	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(136, 136, 136) // dim white
	pdf.CellFormat(0, 5, data.Metadata.GeneratedAt, "", 1, "L", false, 0, "")
	pdf.Ln(8)

	// ── Metadata Section ──────────────────────────────────────────────
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(0, 7, "Session Info", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)

	writePDFMetaRow(pdf, "Device", data.Metadata.DeviceName)
	writePDFMetaRow(pdf, "Platform", data.Metadata.TargetPlatform)
	writePDFMetaRow(pdf, "Application", data.Metadata.AppPackage)
	writePDFMetaRow(pdf, "Build Type", string(data.Metadata.BuildType))
	writePDFMetaRow(pdf, "Duration", fmt.Sprintf("%d samples", data.Summary.DurationSeconds))
	pdf.Ln(6)

	// ── Summary Section ───────────────────────────────────────────────
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(0, 7, "Metrics Summary", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)

	summaryRows := []struct{ label, value string }{
		{"Peak CPU", fmt.Sprintf("%.1f%%", data.Summary.PeakCPUPercent)},
		{"Average CPU", fmt.Sprintf("%.1f%%", data.Summary.AverageCPUPercent)},
		{"Peak Memory", formatPDFBytes(data.Summary.PeakMemoryKB)},
		{"Average Memory", formatPDFBytes(data.Summary.AverageMemoryKB)},
		{"Peak Threads", fmt.Sprintf("%d", data.Summary.PeakThreads)},
	}

	for _, row := range summaryRows {
		writePDFMetaRow(pdf, row.label, row.value)
	}
	pdf.Ln(6)

	// ── CPU Chart ─────────────────────────────────────────────────────
	if len(snapshots) >= 2 {
		pdf.SetFont("Helvetica", "B", 11)
		pdf.SetTextColor(0, 255, 255)
		pdf.CellFormat(0, 6, "CPU Utilization (%)", "", 1, "L", false, 0, "")
		pdf.Ln(2)

		drawPDFLineChart(pdf, snapshots, 170, 50, 0, 100, func(s engine.TelemetrySnapshot) float64 {
			return s.CPUPercent
		})
		pdf.Ln(6)

		// ── Memory Chart ─────────────────────────────────────────────
		var maxMem float64
		for _, s := range snapshots {
			m := float64(s.MemoryKB) / 1024.0
			if m > maxMem {
				maxMem = m
			}
		}
		if maxMem < 100 {
			maxMem = 100
		}

		pdf.SetFont("Helvetica", "B", 11)
		pdf.SetTextColor(255, 0, 255) // magenta
		pdf.CellFormat(0, 6, "Memory Footprint (MB)", "", 1, "L", false, 0, "")
		pdf.Ln(2)

		drawPDFLineChart(pdf, snapshots, 170, 50, 0, maxMem, func(s engine.TelemetrySnapshot) float64 {
			return float64(s.MemoryKB) / 1024.0
		})
		pdf.Ln(6)

		// ── Threads Chart ────────────────────────────────────────────
		var maxThr float64
		for _, s := range snapshots {
			if float64(s.Threads) > maxThr {
				maxThr = float64(s.Threads)
			}
		}
		if maxThr < 10 {
			maxThr = 10
		}

		pdf.SetFont("Helvetica", "B", 11)
		pdf.SetTextColor(0, 255, 0) // green
		pdf.CellFormat(0, 6, "Thread Count", "", 1, "L", false, 0, "")
		pdf.Ln(2)

		drawPDFLineChart(pdf, snapshots, 170, 50, 0, maxThr, func(s engine.TelemetrySnapshot) float64 {
			return float64(s.Threads)
		})
	}

	// ── Footer ───────────────────────────────────────────────────────
	pdf.SetY(-30)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(136, 136, 136)
	pdf.CellFormat(0, 10, fmt.Sprintf("Generated by perfmon v%s", data.Metadata.PerfmonVersion),
		"", 1, "C", false, 0, "")

	return outPath, pdf.OutputFileAndClose(outPath)
}

func writePDFMetaRow(pdf *fpdf.Fpdf, label, value string) {
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(200, 200, 200)
	pdf.CellFormat(40, 6, label, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(0, 6, value, "", 1, "L", false, 0, "")
}

func drawPDFLineChart(pdf *fpdf.Fpdf, snapshots []engine.TelemetrySnapshot, chartWidth, chartHeight float64, dataMin, dataMax float64, valueFn func(engine.TelemetrySnapshot) float64) {
	if len(snapshots) < 2 {
		return
	}

	n := len(snapshots)
	stepX := chartWidth / float64(n-1)
	rangeY := dataMax - dataMin
	if rangeY == 0 {
		rangeY = 1
	}

	// Get current position for chart origin
	x0, y0 := pdf.GetX(), pdf.GetY()

	// Draw axes
	pdf.SetDrawColor(51, 51, 51)
	pdf.SetLineWidth(0.5)
	pdf.Line(x0, y0, x0+chartWidth, y0)           // top
	pdf.Line(x0, y0+chartHeight, x0+chartWidth, y0+chartHeight) // bottom
	pdf.Line(x0, y0, x0, y0+chartHeight)            // left
	pdf.Line(x0+chartWidth, y0, x0+chartWidth, y0+chartHeight) // right

	// Draw dashed grid lines
	pdf.SetDrawColor(50, 50, 50)
	pdf.SetLineWidth(0.3)
	for i := 1; i <= 3; i++ {
		gy := y0 + (chartHeight/4)*float64(i)
		pdf.Line(x0, gy, x0+chartWidth, gy)
	}

	// Draw data line
	pdf.SetLineWidth(1.5)

	// Build points
	type point struct{ x, y float64 }
	points := make([]point, n)
	for i, s := range snapshots {
		x := x0 + float64(i)*stepX
		val := valueFn(s)
		y := y0 + chartHeight - ((val-dataMin)/rangeY)*chartHeight
		if y < y0 {
			y = y0
		}
		if y > y0+chartHeight {
			y = y0 + chartHeight
		}
		points[i] = point{x, y}
	}

	// Draw the line connecting all points
	for i := 1; i < len(points); i++ {
		pdf.Line(points[i-1].x, points[i-1].y, points[i].x, points[i].y)
	}
}

func formatPDFBytes(kb int64) string {
	if kb < 1024 {
		return fmt.Sprintf("%d KB", kb)
	}
	return fmt.Sprintf("%.1f MB", float64(kb)/1024.0)
}
